### ISSUE TITLE
[BUG] Can't find instance moving MO2 -> Vortex

### ISSUE THREAD

**Issue by viktorthesorcerer** [Cutleast/Mod-Manager-Migrator#10]
**Error Message**

Traceback (most recent call last):
  File "E:\Mod Manager Migrator-545-v2-32-1701252368\dialogs.py", line 219, in goto_secnd_page
  File "E:\Mod Manager Migrator-545-v2-32-1701252368\managers.py", line 1233, in load_instances
ValueError: Found no instances!

**To Reproduce**
1. Launch MMM
2. Click on Select source
3. Select Mod Organizer and click next

**Expected behavior**
Find instance

**Comment by Cutleast** [comment]
Please answer the following questions:
1. Does a folder named "ModOrganizer" exist under %LocalAppData%?
2. Is your instance global or portable? Currently, only global instances are supported.
